// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGw_r3lWXPvYDqr4TIv8b_rzu9SiPObt0',
    appId: '1:374924717009:web:d97d4b616ce10c98344ef0',
    messagingSenderId: '374924717009',
    projectId: 'computer-products-app',
    authDomain: 'computer-products-app.firebaseapp.com',
    storageBucket: 'computer-products-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXoPdSffgl1r6ULHGiErYst5Kn1vPNvM',
    appId: '1:374924717009:android:e1d32b643aa136ff344ef0',
    messagingSenderId: '374924717009',
    projectId: 'computer-products-app',
    storageBucket: 'computer-products-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyjaK16YL3ymgYWI1zUzK-DHokmde0-k',
    appId: '1:374924717009:ios:3f06c53f559b0267344ef0',
    messagingSenderId: '374924717009',
    projectId: 'computer-products-app',
    storageBucket: 'computer-products-app.appspot.com',
    iosBundleId: 'com.example.computerProductsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKyjaK16YL3ymgYWI1zUzK-DHokmde0-k',
    appId: '1:374924717009:ios:3f06c53f559b0267344ef0',
    messagingSenderId: '374924717009',
    projectId: 'computer-products-app',
    storageBucket: 'computer-products-app.appspot.com',
    iosBundleId: 'com.example.computerProductsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGw_r3lWXPvYDqr4TIv8b_rzu9SiPObt0',
    appId: '1:374924717009:web:2ff7ad8001d6ea64344ef0',
    messagingSenderId: '374924717009',
    projectId: 'computer-products-app',
    authDomain: 'computer-products-app.firebaseapp.com',
    storageBucket: 'computer-products-app.appspot.com',
  );
}
